Refactor
rosneuro/rosneuro_filters_hamming pull request #1
Opened 2024-05-24 13:32 UTC by mirovix

1. Unit Test completed
2. Integration Test completed
3. Refactoring

2024-06-05 13:06 UTC, PaoloFori requested changes
this package with also the one of hann, blackman and flattop must depend on rosneuro_window and the package's name must be rosneuro_windows_hamming or hann or ...
Hence create new packages: rosneuro_windows, rosneuro_windows_hamming, rosneuro_windows_hann, rosneuro_windows_flattop, rosneuro_windows_blackman. For the code part refer to the repository on neurorobotics, but create new ones in rosneuro (set them private)

2024-06-05 13:06 UTC, PaoloFori commented on CMakeLists.txt
> +					include/${PROJECT_NAME}/)
remove project name

2024-06-06 21:51 UTC, mirovix commented on CMakeLists.txt
> +					include/${PROJECT_NAME}/)
1. Thanks for your detailed instructions. I was planning to create these new packages once your changes are approved. However, if there's a pressing need to do it sooner, please let me know, and I'll prioritize accordingly.

2. Project name removed from "include_directories".

2024-06-10 12:28 UTC, PaoloFori commented on CMakeLists.txt
> +					include/${PROJECT_NAME}/)
create the new packages in order to have a complete version of Rosneuro so that we can test it before making it public

2024-07-05 10:54 UTC, PaoloFori approved these changes

2024-07-05 11:13 UTC, merged